  CREATE TABLE "APP_USERS_MODULES" 
   (	"IDUSER" NUMBER NOT NULL ENABLE, 
	"IDMODULE" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"IDUSERMODULE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "APP_USERS_MODULES_PK" PRIMARY KEY ("IDUSERMODULE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "APP_USERS_MODULES" ADD CONSTRAINT "APP_USERS_MODULES_CON" FOREIGN KEY ("IDMODULE")
	  REFERENCES "APP_MODULES" ("IDMODULE") ENABLE;
  ALTER TABLE "APP_USERS_MODULES" ADD CONSTRAINT "APP_USERS_MODULES_CON2" FOREIGN KEY ("IDUSER")
	  REFERENCES "APP_USERS" ("IDUSER") ENABLE;

  CREATE UNIQUE INDEX "APP_USERS_MODULES_IDX" ON "APP_USERS_MODULES" ("IDUSER", "IDMODULE") 
  ;

   COMMENT ON TABLE "APP_USERS_MODULES"  IS 'Usuario por modulo';