  CREATE TABLE "PEDIDO_CAB" 
   (	"PEDIDO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"LOJA_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLIENTE_ID" NUMBER(10,0), 
	"TIPO_ENTREGA" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"TIPO_ORIGEM" VARCHAR2(1 CHAR) NOT NULL ENABLE,
    "VALOR_TOTAL" NUMBER(10,2), 	
	"STATUS" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"USER_ENTRADA" NUMBER(10,0), 
	"DATA_ENTRADA" TIMESTAMP (6) DEFAULT sysdate, 
	"USER_ANALISE" NUMBER(10,0), 
	"DATA_ANALISE" TIMESTAMP (6) , 
	"USER_PREPARACAO" NUMBER(10,0), 
	"DATA_PREPARACAO" TIMESTAMP (6) , 
	"USER_ENTREGA" NUMBER(10,0), 
	"DATA_ENTREGA" TIMESTAMP (6) , 
	"USER_CONCLUIDO" NUMBER(10,0), 
	"DATA_CONCLUIDO" TIMESTAMP (6) , 
	"USER_CALEDADO" NUMBER(10,0), 
	"DATA_CANCELADO" TIMESTAMP (6) , 
	 CONSTRAINT "PEDIDO_CAB_PK" PRIMARY KEY ("PEDIDO_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PEDIDO_CAB" ADD CONSTRAINT "PEDIDO_CAB_CON01" FOREIGN KEY ("LOJA_ID")
	  REFERENCES "CAD_LOJA" ("LOJA_ID") ENABLE;
  ALTER TABLE "PEDIDO_CAB" ADD CONSTRAINT "PEDIDO_CAB_CON02" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CAD_CLIENTE" ("CLIENTE_ID") ON DELETE SET NULL ENABLE;

  CREATE INDEX "PEDIDO_CAB_IDX01" ON "PEDIDO_CAB" ("LOJA_ID", "CLIENTE_ID") 
  ;

   COMMENT ON COLUMN "PEDIDO_CAB"."TIPO_ENTREGA" IS 'E - entrega / R - retirada';
   COMMENT ON COLUMN "PEDIDO_CAB"."TIPO_ORIGEM" IS 'B - balcao / O - OnLIne / I - Ifood';
   COMMENT ON COLUMN "PEDIDO_CAB"."STATUS" IS '1-Analise/2-preparacao/3-entrega/4-concluido/5-cancelado';
   COMMENT ON TABLE "PEDIDO_CAB"  IS 'Pedios da loja';

  CREATE OR REPLACE EDITIONABLE TRIGGER "PEDIDO_CAB_TRG" 
before
insert or update or delete on "PEDIDO_CAB"
for each row
begin
  if inserting then 
    if :new.PEDIDO_ID is null then 
      select PEDIDO_CAB_SEQ.nextval into :new.PEDIDO_ID from dual; 
    end if; 
  end if; 
end;
/
ALTER TRIGGER "PEDIDO_CAB_TRG" ENABLE;